"""add subdomain to tenant table

Revision ID: 1f767f7b8220
Revises: bebfa1768e87
Create Date: 2026-05-08 08:32:02.440475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "1f767f7b8220"
down_revision: Union[str, None] = "bebfa1768e87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants",
        sa.Column("subdomain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_unique_constraint(None, "tenants", ["subdomain"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tenants", type_="unique")
    op.drop_column("tenants", "subdomain")
    # ### end Alembic commands ###
