"""add description and image to service table

Revision ID: 2b38f38d5551
Revises: 82ee30db94ab
Create Date: 2026-05-07 14:37:56.773842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2b38f38d5551"
down_revision: Union[str, None] = "82ee30db94ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "services",
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "image")
    op.drop_column("services", "description")
    # ### end Alembic commands ###
