"""tenant_id to tables

Revision ID: 62cd90e86a45
Revises: 60e8395cc2bb
Create Date: 2026-05-05 09:03:28.794545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cd90e86a45'
down_revision: Union[str, None] = '60e8395cc2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.add_column('clients', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.add_column('professionals', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professionals', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.add_column('services', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'tenant_id')
    op.drop_constraint(None, 'professionals', type_='foreignkey')
    op.drop_column('professionals', 'tenant_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'tenant_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'tenant_id')
    # ### end Alembic commands ###
