"""Social media links to tenant table

Revision ID: bebfa1768e87
Revises: 2b38f38d5551
Create Date: 2026-05-08 07:26:16.784501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "bebfa1768e87"
down_revision: Union[str, None] = "2b38f38d5551"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants",
        sa.Column(
            "instagram_profile", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "facebook_profile", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "facebook_profile")
    op.drop_column("tenants", "instagram_profile")
    # ### end Alembic commands ###
