"""Appointment: start_time and end_time

Revision ID: d9861d2cc2b8
Revises: f2e24c1b0dbd
Create Date: 2025-03-24 10:06:53.716322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9861d2cc2b8'
down_revision: Union[str, None] = 'f2e24c1b0dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column(
        'start_time', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column(
        'end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    # ### end Alembic commands ###
